server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
    servise-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost